name: Daily Playlist Update

on:
  schedule:
    # Run daily at 6 AM UTC (adjust timezone as needed)
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual runs

jobs:
  update-playlists:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Cache application data
      uses: actions/cache@v3
      with:
        path: |
          cache
          spotify_cache
        key: ${{ runner.os }}-app-cache-v1
        restore-keys: |
          ${{ runner.os }}-app-cache-
        
    - name: Build application
      run: cargo build --release
      
    - name: Run playlist update
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
      run: |
        # Run for yesterday's date (default behavior)
        ./target/release/spinitron-scraper --spotify
        
    - name: Generate playlist markdown
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
      run: |
        ./target/release/spinitron-scraper --list-playlists --spotify > kalx-playlists.md
        
    - name: Commit and push updated playlist list
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add kalx-playlists.md
        if ! git diff --cached --quiet; then
          git commit -m "Update playlist list - $(date '+%Y-%m-%d')"
          git push
        else
          echo "No changes to commit"
        fi