name: Daily Playlist Update

on:
  schedule:
    # Run daily at 6 AM UTC (adjust timezone as needed)
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual runs

jobs:
  update-playlists:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Cache track search data
      uses: actions/cache@v3
      with:
        path: |
          cache
          spotify_cache/track_cache.json
        key: ${{ runner.os }}-track-cache-v1
        restore-keys: |
          ${{ runner.os }}-track-cache-
        
    - name: Build application
      run: cargo build --release
      
    - name: Run playlist update
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
      run: |
        # Run for yesterday's date (default behavior)
        ./target/release/spinitron-scraper --spotify
        
    - name: Report completion
      run: |
        echo "✅ Playlist update completed successfully"
        echo "📅 Run date: $(date)"